import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import { Footer } from "@/components/shared/footer/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Freej Trivia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
        // style={{
        //   background:
        //     "var(--back-2, linear-gradient(181deg, #FE3131 0.62%, #FF7D36 47.14%, #FF8937 99.35%))",
        //   backgroundRepeat: "no-repeat",
        // }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
